ONME-3861 Update DNS classes and DNS module to support interface name
tymoteuszblochmobica/mbed-os pull request #4
Opened 2018-11-14 17:03 UTC by tymoteuszblochmobica

ONME-3862  Change lwip DNS functionality so that only default network interface updates DNS addresses in lwip global DNS storage

### Description

### Pull request type

    [ ] Fix
    [ ] Refactor
    [ ] Target update
    [ x] Functionality change
    [ ] Docs update
    [ ] Test update
    [ ] Breaking change

2018-11-14 17:06 UTC, tymoteuszblochmobica commented
@Seppo please review

2018-11-14 17:11 UTC, tymoteuszblochmobica commented
@mikaleppanen please review

2018-11-14 17:12 UTC, tymoteuszblochmobica commented
@kjbracey-arm  please review

2018-11-15 10:55 UTC, mikaleppanen commented on features/netsocket/nsapi_dns.cpp
> +    nsapi_size_or_error_t result = nsapi_dns_query_multiple(stack, host, &addr, 1, version);//to be finished for interface name
Add interface name

2018-11-15 10:55 UTC, mikaleppanen commented on features/netsocket/nsapi_dns.cpp
> +        err = nsapi_dns_get_server_addr(stack, &index, &total_attempts, &send_success, &dns_addr,"to be done");
Add interface name

2018-11-15 10:55 UTC, mikaleppanen commented on features/netsocket/nsapi_dns.cpp
> +    return nsapi_dns_query_multiple_async(stack, host, callback, 0, call_in_cb, version);//to be finished for interface name
Add interface name.

2018-11-15 10:55 UTC, mikaleppanen commented on features/lwipstack/LWIPInterface.cpp
> +    sprintf(buf,"%c%c%d",netif.name[0],netif.name[1],netif.num);
Correct to work with different lengths of the interface name.

2018-11-19 15:28 UTC, tymoteuszblochmobica commented on features/netsocket/nsapi_dns.cpp
> +    nsapi_size_or_error_t result = nsapi_dns_query_multiple(stack, host, &addr, 1, version);//to be finished for interface name
done

2018-11-20 07:50 UTC, mikaleppanen requested changes
Correct indentation errors so comparing files will possible.

2018-11-20 07:50 UTC, mikaleppanen commented on features/lwipstack/lwip/src/core/ipv4/lwip_dhcp.c
> +    DHCP_OPTION_IDX_OVERLOAD = 0,
Correct indentation.

2018-11-20 07:50 UTC, mikaleppanen commented on features/lwipstack/lwip/src/core/ipv4/lwip_dhcp.c
> +    DHCP_OPTION_IDX_OVERLOAD = 0,
Correct all  indentation errors in file, so compare is possible.

2018-11-20 07:50 UTC, mikaleppanen commented on features/lwipstack/lwip/src/core/lwip_dns.c
> - *
Correct all indentation errors in this file.

2018-11-20 13:18 UTC, mikaleppanen requested changes

2018-11-20 13:18 UTC, mikaleppanen commented on features/lwipstack/lwip/src/core/ipv4/lwip_dhcp.c
> +    dns_setserver(n, &dns_addr, _interface_name);
Provide here the "netif" to dns module which then needs to check based on "netif" content to whether interface is multihoming or default.

2018-11-20 13:18 UTC, mikaleppanen commented on features/lwipstack/lwip/src/core/ipv4/lwip_dhcp.c
> +dhcp_start(struct netif *netif, const char *interface_name)
Do not change dhcp start interface.

2018-11-21 15:14 UTC, mikaleppanen requested changes

2018-11-21 15:14 UTC, mikaleppanen commented on features/lwipstack/lwipopts.h
> +#define LWIP_RAW                    1
Why is this needed?

2018-11-23 12:20 UTC, tymoteuszblochmobica commented on features/lwipstack/lwipopts.h
> +#define LWIP_RAW                    1
changed

2018-11-23 12:26 UTC, tymoteuszblochmobica commented on features/lwipstack/lwip/src/core/ipv4/lwip_dhcp.c
> +    dns_setserver(n, &dns_addr, _interface_name);
done

2018-11-23 12:29 UTC, mikaleppanen approved these changes

2018-12-18 15:29 UTC, closed without merging