ONME-3984 Refactor IP_Route for interface name Initial release
tymoteuszblochmobica/mbed-os pull request #5
Opened 2018-11-23 16:28 UTC by tymoteuszblochmobica

### Description
Initial release.  
To do: set netif to PCB  for ICMP

### Pull request type

    [ ] Fix
    [ ] Refactor
    [ ] Target update
    [x] Functionality change
    [ ] Docs update
    [ ] Test update
    [ ] Breaking change

2018-11-23 16:30 UTC, tymoteuszblochmobica commented
@mikaleppanen please review

2018-11-23 16:31 UTC, tymoteuszblochmobica commented
@seppo please review

2018-11-23 16:32 UTC, tymoteuszblochmobica commented
@kjbracey-arm please review

2018-11-26 12:15 UTC, mikaleppanen requested changes

2018-11-26 12:15 UTC, mikaleppanen commented on features/lwipstack/lwip/src/core/ipv4/lwip_icmp.c
> +  sprintf(name, "%c%c%d", p->netif->name[0], p->netif->name[1], p->netif->num);
This is made in several places so I think there should be helper functions for this. Also the p->netif->num is running from 0 to 255 so more space should be reserved for it.

2018-12-18 15:28 UTC, closed without merging